Exercise 1.15: The sine of an angle (speci\ufb01ed in radians) can be computed by
making use of the approximation sin x approx x if x is su\ufb03ciently small, and
the trigonometric identity
                        x               x
      sin x = 3 sin --- - 4 sin^3 ---
                        3               3
to reduce the size of the argument of sin. (For purposes of this exercise an
angle is considered \u201csu\ufb03ciently small\u201d if its magnitude is not greater than 0.1
radians.) These ideas are incorporated in the following procedures:
       (define (cube x) (* x x x))
       (define (p x) (- (* 3 x) (* 4 (cube x))))
       (define (sine angle)
           (if (not (> (abs angle) 0.1))
                angle
     
                (p (sine (/ angle 3.0)))))
       
----       
a. How many times is the procedure p applied when (sine 12.15) is evalu-
     ated?

p is applied until angle is lesser than or equal to 0.1. So, if N is number of evaluations, 

12.5/3^n > 0.1
12.5 > 0.1 * 3^n
125 > 3^n
n < log3 125 < 5

Answer requires 5 applications of p. For example, (sine 0.3) requires n = log3 3 = 1 application.

-----
b. What is the order of growth in space and number of steps (as a function
     of a ) used by the process generated by the sine procedure when (sine a)
     is evaluated?

Space, time: O(log3 n)
